Usuario.jsx:583 
 
 PATCH http://localhost:3000/usuarios/5 404 (Not Found)
Usuario.jsx:598 
 Error al restablecer la contraseña: 
AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_REQUEST"
config
: 
{transitional: {…}, adapter: Array(3), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"Request failed with status code 404"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta char…e>Cannot PATCH /usuarios/5</pre>\n</body>\n</html>\n', status: 404, statusText: 'Not Found', headers: AxiosHeaders, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 404\n    at settle (http://localhost:3001/static/js/2.chunk.js:94823:12)\n    at XMLHttpRequest.onloadend (http://localhost:3001/static/js/2.chunk.js:93508:70)\n    at Axios.request (http://localhost:3001/static/js/2.chunk.js:93986:41)\n    at async resetPassword (http://localhost:3001/static/js/main.chunk.js:13315:7)"
[[Prototype]]
: 
Error
constructor
: 
ƒ AxiosError(message, code, config, request, response)
toJSON
: 
ƒ toJSON()
isAxiosError
: 
true
[[Prototype]]
: 
Object
